Update the build tools and the Windows toolchain
Upgrade to OpenJDK 19.0.2, Apache Ant 1.10.13, and CMake 3.26.3.

Downgrade to Microsoft Visual Studio Build Tools 2022 version 17.1.0
to avoid Bug JDK-8306887, "Error C2327 while compiling WebKit on
Windows with Visual Studio 2022 17.5." For details, see:

  https://bugs.openjdk.org/browse/JDK-8306887